/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActionMenu: typeof import('./src/components/partials/ActionMenu.vue')['default']
    BaseToast: typeof import('./src/components/partials/BaseToast.vue')['default']
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    Card: typeof import('./src/components/ui/card/Card.vue')['default']
    CardContent: typeof import('./src/components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./src/components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./src/components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./src/components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./src/components/ui/card/CardTitle.vue')['default']
    Carousel: typeof import('./src/components/ui/carousel/Carousel.vue')['default']
    CarouselContent: typeof import('./src/components/ui/carousel/CarouselContent.vue')['default']
    CarouselItem: typeof import('./src/components/ui/carousel/CarouselItem.vue')['default']
    CarouselNext: typeof import('./src/components/ui/carousel/CarouselNext.vue')['default']
    CarouselPrevious: typeof import('./src/components/ui/carousel/CarouselPrevious.vue')['default']
    Input: typeof import('./src/components/ui/input/Input.vue')['default']
    ListCarousel: typeof import('./src/components/partials/ListCarousel.vue')['default']
    MainNavbar: typeof import('./src/components/partials/MainNavbar.vue')['default']
    Menubar: typeof import('./src/components/ui/menubar/Menubar.vue')['default']
    MenubarCheckboxItem: typeof import('./src/components/ui/menubar/MenubarCheckboxItem.vue')['default']
    MenubarContent: typeof import('./src/components/ui/menubar/MenubarContent.vue')['default']
    MenubarGroup: typeof import('./src/components/ui/menubar/MenubarGroup.vue')['default']
    MenubarItem: typeof import('./src/components/ui/menubar/MenubarItem.vue')['default']
    MenubarLabel: typeof import('./src/components/ui/menubar/MenubarLabel.vue')['default']
    MenubarMenu: typeof import('./src/components/ui/menubar/MenubarMenu.vue')['default']
    MenubarRadioGroup: typeof import('./src/components/ui/menubar/MenubarRadioGroup.vue')['default']
    MenubarRadioItem: typeof import('./src/components/ui/menubar/MenubarRadioItem.vue')['default']
    MenubarSeparator: typeof import('./src/components/ui/menubar/MenubarSeparator.vue')['default']
    MenubarShortcut: typeof import('./src/components/ui/menubar/MenubarShortcut.vue')['default']
    MenubarSub: typeof import('./src/components/ui/menubar/MenubarSub.vue')['default']
    MenubarSubContent: typeof import('./src/components/ui/menubar/MenubarSubContent.vue')['default']
    MenubarSubTrigger: typeof import('./src/components/ui/menubar/MenubarSubTrigger.vue')['default']
    MenubarTrigger: typeof import('./src/components/ui/menubar/MenubarTrigger.vue')['default']
    MovieCard: typeof import('./src/components/partials/movie/MovieCard.vue')['default']
    MovieCarousel: typeof import('./src/components/partials/MovieCarousel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tooltip: typeof import('./src/components/ui/tooltip/Tooltip.vue')['default']
    TooltipContent: typeof import('./src/components/ui/tooltip/TooltipContent.vue')['default']
    TooltipProvider: typeof import('./src/components/ui/tooltip/TooltipProvider.vue')['default']
    TooltipTrigger: typeof import('./src/components/ui/tooltip/TooltipTrigger.vue')['default']
    TvCarousel: typeof import('./src/components/partials/TvCarousel.vue')['default']
    WatchlistCarousel: typeof import('./src/components/partials/WatchlistCarousel.vue')['default']
  }
}
